# Default values for python.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 2
image:
  repository: microsoft/aspnetcore-build
  tag: 2.0
  pullPolicy: IfNotPresent
service:
  name: dotnetcore
  type: NodePort
  externalPort: 80
  internalPort: 30090
resources:
  limits:
    cpu: 1
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 256Mi
configmap:
    name: taskapi-config
volumes:
    volume: configvolume
data:
    baseUri: "http://192.168.137.87:30090"
    tapiserviceversion: mongo
